### PR TITLE
This code fixes a few problems when processing some datasets

### PR DESCRIPTION
**Pull request by rncampos**
(1)
The commit from Mar 25 on Utils.py is very important as there are some encoding problems with a few datasets. This code fixes that.

(2) The commit from Mar 25 on Base.py loads stopwords from NLTK.  As for now, only stopwords from 3 different languages are being loaded. There was also an error when processing texts, other than the few languages that were initially defined in the 'ISO_to_language' dictionary. This was corrected.

(3) The commit from Mar 27 on Base.py created a dictionary for the iso languages that can be processed by the Snowball Stemmer

(4) The commit from Mar 31 on api.py: Kea is launching an exception for texts where there are no candidates (for instance, texts that are solely formed by punctuation marks or emojis). This was fixed in this code

(5) The commit on Nov 18 on utils.pt has already been fixed by Florian on his code.

I have already run this code on top of 20 datasets through all the algorithms provided by PKE and it doesn't crashes. Instead, running them through the current available PKE version leads to a few crashes particularly due to encoding problems in processing several datasets. If these commits are accepted all the problems will be fixed.

### CODE REVIEW

**Comment by ygorg** [comment]
Hi,
I worked on this pull request, but as many commits were made on `pke` since, I took the liberty of working on it here ([ygorg/pke - fixes](https://github.com/ygorg/pke/commits/fixes)), this also allowed to fix issues more globally.

The contributions of this pull request I identified are as follow:
- Replacing hard coded UNIX dependent paths by `os.path` functions.
- Preventing exceptions when model has no candidate (here in `feature_scaling`).
- Creating/Loading models can lead to encoding errors. This is because Creating/Loading is sometime unconsistent.
  - Exemple: `load_document_frequency_file` open the file without specified encoding, but `compute_document_frequency` is creating the file while specifying the encoding (`utf-8`).
- Improving language support, using a ressource only if it exist. These ressources are spacy, the stemmer and the stopwords.
  - _I'm just thinking out loud here._ I'm still trying to figure out what is a good way of handling the language support in `pke`. As of now the POSTag is used in many models and candidate selection. But the only languages which `pke` support are really the ones supported by `CoreNLP` and `spacy` (maybe taking inputs from `treetagger` would be an improvement for language support / preprocessing comparison).

Thank you for pointing out these issues !

**Comment by rncampos** [comment]
Dear ygor,

I have already tried the ygorg/pke-fixes code but the problem still remains. I have already sent to your email the solutions to all the problems found.

Can you please let me know when do you plan to release pke-fixes?

Best
Ricardo

De: _ygor_gallina <notifications@github.com>
Enviada: 10 de junho de 2020 17:32
Para: boudinfl/pke <pke@noreply.github.com>
Cc: Ricardo Campos <ricardo.campos@ipt.pt>; Author <author@noreply.github.com>
Assunto: Re: [boudinfl/pke] This code fixes a few problems when processing some datasets (#106)


Hi, thanks for your response,
Could you provide more information on the error that occurs (like where and what exception is raised) ?
Have you tried with the code at ygorg/pke - fixes<https://github.com/ygorg/pke/commits/fixes> (that you can install using python3 -m pip install https://github.com/ygorg/pke/archive/fixes.zip), as it is not yet included in the pip version.
I didn't receive the SemEval-2017 dataset you are referring to, as this message was received on Github (not by mail).

**Comment by jnothman** [comment]
@ygorg, I note that your `fixes` branch requires the `langcodes` packages, but it is not added as a requirement for setup.py

**Comment by ygorg** [comment]
I merged #141 which fixes the issues adressed in this PR.
Please use the new `encoding` parameter (available in every function that open files) if facing encoding errors.

**Pull request closed without merging**
