### PR TITLE
Update readers.py function (list_linked_spacy_models) to work with spacy version > 3.

### PR DESCRIPTION
**Pull request by Vaibhavbrkn**

### CODE REVIEW

**Comment by ygorg** [comment]
Hi, thank you for taking the time to make this PR.
Though I don't see why it is needed.
As far as I know the code at [readers.py#L114](https://github.com/boudinfl/pke/blob/49d3522849cf598f24be9ed102be66f720963fca/pke/readers.py#L114) solves the problem of listing downloaded models for both spacy v3 and before.

Did you encounter an error that was solved by the code you propose ?

**Comment by Vaibhavbrkn** [comment]
it did not work for spacy version 3.0.6, and yeah using this code error was solved. as in spacy 3.0.6 instead of "Location" it is "location".

**Comment by ygorg** [comment]
I just tried the following code:
```bash 
virtualenv -p python3.7 test-pke
source test-pke/bin/activate
python -m pip install git+https://github.com/boudinfl/pke
python -c "import spacy; print(spacy.__version__); import pke; e = pke.LoadFile(); e.load_document('hello, who are you ?')"
python -m spacy download en_core_web_sm
python -c "import spacy; print(spacy.__version__); import pke; e = pke.LoadFile(); e.load_document('hello, who are you ?')"
rm -rf test-pke
```
The first call to `python -c` raise an error because it cannot find an 'en' model as expected
The second work a expected.

I don't understand the need to make `list_linked_spacy_models` work for spacy v3 because as of v3 spacy forbids to create links, so there cannot be linked models therefore using `list_linked_spacy_models` is pointless.
Also [this chunk of code](https://github.com/boudinfl/pke/blob/49d3522849cf598f24be9ed102be66f720963fca/pke/readers.py#L110) prevents the `list_linked_spacy_models` to be used with spacy v3, so no problems should arise.

What is the error you encountered, where did it happen and what code raised that error ?

**Comment by ygorg** [comment]
You might not have the latest version of pke. Please try reinstalling it. If the error persists I'll accept this PR.

**Comment by Vaibhavbrkn** [comment]
OK! Now it works just need to use full model name instead of just language name for spacy version > 3. Thanks :)

**Pull request closed without merging**
